let stockProductos = [
    {id: 1, nombre: "Caligrafia basica 1", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia estandar", precio: 1000, img: './img/GI-1.jpg'},
    {id: 2, nombre: "Caligrafia basica 2", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia gotica", precio: 1100, img: './img/GI-1.jpg'},
    {id: 3, nombre: "Caligrafia basica 3", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia dibujada", precio: 1200, img: './img/GI-1.jpg'},
    {id: 4, nombre: "Caligrafia media 1", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia estandar", precio: 1400, img: './img/GI-2.jpg'},
    {id: 5, nombre: "Caligrafia media 2", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia gotica", precio: 1600, img: './img/GI-2.jpg'},
    {id: 6, nombre: "Caligrafia media 3", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia dibujada", precio: 1800, img: './img/GI-2.jpg'},
    {id: 7, nombre: "Caligrafia avanzada 1", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia estandar", precio: 2000, img: './img/GI-3.jpg'},
    {id: 8, nombre: "Caligrafia avanzada 2", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia gotica", precio: 2500, img: './img/GI-3.jpg'},
    {id: 9, nombre: "Caligrafia avanzada 3", tipo: "curso intensivo", cantidad: 1, desc: "Caligfrafia dibujada", precio: 3000, img: './img/GI-3.jpg'},
    {id: 10, nombre: "Caricaturas inicial 1", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 1", precio: 1200, img: './img/GI-4.jpg'},
    {id: 11, nombre: "Caricaturas inicial 2", tipo: "curso intensivo", cantidad: 1,desc: "Simpsons 2", precio: 1400, img: './img/GI-4.jpg'},
    {id: 12, nombre: "Caricaturas inicial 3", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 3", precio: 1600, img: './img/GI-4.jpg'},
    {id: 13, nombre: "Caricaturas avanzado 1", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 1", precio: 1800, img: './img/GI-5.jpg'},
    {id: 14, nombre: "Caricaturas avanzado 2", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 2", precio: 2000, img: './img/GI-5.jpg'},
    {id: 15, nombre: "Caricaturas avanzado 3", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 3", precio: 2200, img: './img/GI-5.jpg'},
    {id: 16, nombre: "Caricaturas superior 1", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 1", precio: 2500, img: './img/GI-6.jpg'},
    {id: 17, nombre: "Caricaturas superior 2", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 2", precio: 3000, img: './img/GI-6.jpg'},
    {id: 18, nombre: "Caricaturas superior 3", tipo: "curso intensivo", cantidad: 1, desc: "Simpsons 3", precio: 3500, img: './img/GI-6.jpg'},
    {id: 19, nombre: "Rostros Inicial", tipo: "curso intensivo", cantidad: 1, desc: "Rostros famosos", precio: 3500, img: './img/GI-7.jpg'},
    {id: 20, nombre: "Rostros Avanzado", tipo: "curso intensivo", cantidad: 1, desc: "Rostros famosos", precio: 4000, img: './img/GI-7.jpg'},
    {id: 20, nombre: "Rostros Superior", tipo: "curso superior", cantidad: 1, desc: "Rostros famosos", precio: 4500, img: './img/GI-7.jpg'},
]